/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appkonversikecepatan;

/**
 *
 * @author T480
 */
public class KonversiKecepatan extends javax.swing.JFrame {

    /**
     * Creates new form KonversiKecepatan
     */
    public KonversiKecepatan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblF = new javax.swing.JLabel();
        txtValfrom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtValto = new javax.swing.JTextField();
        lblT = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rbMeterPerDetikF = new javax.swing.JRadioButton();
        lblFrom = new javax.swing.JLabel();
        lblTo = new javax.swing.JLabel();
        rbKilometerPerJamF = new javax.swing.JRadioButton();
        rbMilPerJamF = new javax.swing.JRadioButton();
        rbKnotF = new javax.swing.JRadioButton();
        rbKakiPerDetikF = new javax.swing.JRadioButton();
        rbMeterPerDetikT = new javax.swing.JRadioButton();
        rbKilometerPerJamT = new javax.swing.JRadioButton();
        rbMilPerJamT = new javax.swing.JRadioButton();
        rbKnotT = new javax.swing.JRadioButton();
        rbKakiPerDetikT = new javax.swing.JRadioButton();
        btnHitung = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("APLIKASI KONVERSI SATUAN KECEPATAN");

        lblF.setText("m/s");

        txtValfrom.setText("1");

        jLabel3.setText("From");

        jLabel4.setText("=");

        txtValto.setText("1");

        lblT.setText("m/s");

        jLabel6.setText("To");

        buttonGroup1.add(rbMeterPerDetikF);
        rbMeterPerDetikF.setSelected(true);
        rbMeterPerDetikF.setText("Meter per detik (m/s)");
        rbMeterPerDetikF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMeterPerDetikFActionPerformed(evt);
            }
        });

        lblFrom.setText("Meter per detik");

        lblTo.setText("Meter per detik");

        buttonGroup1.add(rbKilometerPerJamF);
        rbKilometerPerJamF.setText("Kilometer per jam (km/jam)");
        rbKilometerPerJamF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbKilometerPerJamFActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbMilPerJamF);
        rbMilPerJamF.setText("Mil per jam (mph)");
        rbMilPerJamF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMilPerJamFActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbKnotF);
        rbKnotF.setText("Knot (kt)");
        rbKnotF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbKnotFActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbKakiPerDetikF);
        rbKakiPerDetikF.setText("Kaki per detik (ft/s)");
        rbKakiPerDetikF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbKakiPerDetikFActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbMeterPerDetikT);
        rbMeterPerDetikT.setSelected(true);
        rbMeterPerDetikT.setText("Meter per detik (m/s)");
        rbMeterPerDetikT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMeterPerDetikTActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbKilometerPerJamT);
        rbKilometerPerJamT.setText("Kilometer per jam (km/jam)");
        rbKilometerPerJamT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbKilometerPerJamTActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbMilPerJamT);
        rbMilPerJamT.setText("Mil per jam (mph)");
        rbMilPerJamT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMilPerJamTActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbKnotT);
        rbKnotT.setText("Knot (kt)");
        rbKnotT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbKnotTActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbKakiPerDetikT);
        rbKakiPerDetikT.setText("Kaki per detik (ft/s)");
        rbKakiPerDetikT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbKakiPerDetikTActionPerformed(evt);
            }
        });

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(lblFrom)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtValfrom, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblF)
                                .addGap(59, 59, 59)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtValto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblT))
                            .addComponent(jLabel6)
                            .addComponent(lblTo))
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbMeterPerDetikF)
                            .addComponent(rbKilometerPerJamF)
                            .addComponent(rbMilPerJamF)
                            .addComponent(rbKnotF)
                            .addComponent(rbKakiPerDetikF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbMeterPerDetikT)
                            .addComponent(rbKilometerPerJamT)
                            .addComponent(rbMilPerJamT)
                            .addComponent(rbKnotT)
                            .addComponent(rbKakiPerDetikT))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(btnHitung)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFrom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValfrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblF)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbMeterPerDetikF)
                        .addGap(18, 18, 18)
                        .addComponent(rbKilometerPerJamF)
                        .addGap(18, 18, 18)
                        .addComponent(rbMilPerJamF)
                        .addGap(18, 18, 18)
                        .addComponent(rbKnotF)
                        .addGap(18, 18, 18)
                        .addComponent(rbKakiPerDetikF))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbMeterPerDetikT)
                        .addGap(18, 18, 18)
                        .addComponent(rbKilometerPerJamT)
                        .addGap(18, 18, 18)
                        .addComponent(rbMilPerJamT)
                        .addGap(18, 18, 18)
                        .addComponent(rbKnotT)
                        .addGap(18, 18, 18)
                        .addComponent(rbKakiPerDetikT)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(btnHitung)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbMeterPerDetikFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMeterPerDetikFActionPerformed
    lblFrom.setText("Meter per detik");
    lblF.setText("m/s");
    }//GEN-LAST:event_rbMeterPerDetikFActionPerformed

    private void rbKilometerPerJamFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbKilometerPerJamFActionPerformed
    lblFrom.setText("Kilometer per jam");
    lblF.setText("km/jam");
    }//GEN-LAST:event_rbKilometerPerJamFActionPerformed

    private void rbMilPerJamFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMilPerJamFActionPerformed
    lblFrom.setText("Mil per jam");
    lblF.setText("mph");
    }//GEN-LAST:event_rbMilPerJamFActionPerformed

    private void rbKnotFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbKnotFActionPerformed
    lblFrom.setText("Knot");
    lblF.setText("kt");
    }//GEN-LAST:event_rbKnotFActionPerformed

    private void rbKakiPerDetikFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbKakiPerDetikFActionPerformed
    lblFrom.setText("Kaki per detik");
    lblF.setText("ft/s");
    }//GEN-LAST:event_rbKakiPerDetikFActionPerformed

    private void rbMeterPerDetikTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMeterPerDetikTActionPerformed
    lblTo.setText("Meter per detik");
    lblT.setText("m/s");
    }//GEN-LAST:event_rbMeterPerDetikTActionPerformed

    private void rbKilometerPerJamTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbKilometerPerJamTActionPerformed
    lblTo.setText("Kilometer per jam");
    lblT.setText("km/jam");
    }//GEN-LAST:event_rbKilometerPerJamTActionPerformed

    private void rbMilPerJamTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMilPerJamTActionPerformed
    lblTo.setText("Mil per jam");
    lblT.setText("mph");
    }//GEN-LAST:event_rbMilPerJamTActionPerformed

    private void rbKnotTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbKnotTActionPerformed
    lblTo.setText("Knot");
    lblT.setText("kt");
    }//GEN-LAST:event_rbKnotTActionPerformed

    private void rbKakiPerDetikTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbKakiPerDetikTActionPerformed
    lblTo.setText("Kaki per detik");
    lblT.setText("ft/s");
    }//GEN-LAST:event_rbKakiPerDetikTActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
    try {
        double kecepatanAwal = Double.parseDouble(txtValfrom.getText());
        
        // Deteksi satuan kecepasan asal
        String satuanAsal = "";
        if (rbMeterPerDetikF.isSelected()) satuanAsal = "m/s";
        else if (rbKilometerPerJamF.isSelected()) satuanAsal = "km/jam";
        else if (rbMilPerJamF.isSelected()) satuanAsal = "mph";
        else if (rbKnotF.isSelected()) satuanAsal = "knot";
        else if (rbKakiPerDetikF.isSelected()) satuanAsal = "ft/s";
        
        // Deteksi satuan kecepatan tujuan
        String satuanTujuan = "";
        if (rbMeterPerDetikT.isSelected()) satuanTujuan = "m/s";
        else if (rbKilometerPerJamT.isSelected()) satuanTujuan = "km/jam";
        else if (rbMilPerJamT.isSelected()) satuanTujuan = "mph";
        else if (rbKnotT.isSelected()) satuanTujuan = "knot";
        else if (rbKakiPerDetikT.isSelected()) satuanTujuan = "ft/s";

        // Konversi input ke m/s
        double kecepatanMS = 0;
        kecepatanMS = switch (satuanAsal) {
            case "km/jam" -> kecepatanAwal * 0.27778;
            case "m/s" -> kecepatanAwal;
            case "mph" -> kecepatanAwal * 0.44704;
            case "knot" -> kecepatanAwal * 0.51444;
            case "ft/s" -> kecepatanAwal * 0.3048;
            default -> kecepatanAwal;
        };
        
        // Konversi dari m/s ke tujuan
        double kecepatanHasil = 0;
        kecepatanHasil = switch (satuanTujuan) {
            case "m/s" -> kecepatanMS;
            case "km/jam" -> kecepatanMS * 3.6;
            case "mph" -> kecepatanMS * 2.23694;
            case "knot" -> kecepatanMS * 1.94384;
            case "ft/s" -> kecepatanMS / 0.3048;
            default -> kecepatanMS;
        };

        txtValto.setText(String.format("%.4f", kecepatanHasil));
    } catch(NumberFormatException e) {
        txtValto.setText("Input tidak valid!");
    }
    }//GEN-LAST:event_btnHitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiKecepatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiKecepatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiKecepatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiKecepatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiKecepatan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblF;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblT;
    private javax.swing.JLabel lblTo;
    private javax.swing.JRadioButton rbKakiPerDetikF;
    private javax.swing.JRadioButton rbKakiPerDetikT;
    private javax.swing.JRadioButton rbKilometerPerJamF;
    private javax.swing.JRadioButton rbKilometerPerJamT;
    private javax.swing.JRadioButton rbKnotF;
    private javax.swing.JRadioButton rbKnotT;
    private javax.swing.JRadioButton rbMeterPerDetikF;
    private javax.swing.JRadioButton rbMeterPerDetikT;
    private javax.swing.JRadioButton rbMilPerJamF;
    private javax.swing.JRadioButton rbMilPerJamT;
    private javax.swing.JTextField txtValfrom;
    private javax.swing.JTextField txtValto;
    // End of variables declaration//GEN-END:variables
}
